"""initial

Revision ID: 982bf9b83b5e
Revises: 
Create Date: 2026-03-15 13:33:01.981996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982bf9b83b5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('github_id', sa.String(length=255), nullable=False),
    sa.Column('nick_name', sa.String(length=255), nullable=False),
    sa.Column('repository_name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.String(length=1), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updatedAt', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('nick_name')
    )
    op.create_table('Commit',
    sa.Column('commit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('commit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('commit_url', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=255), nullable=False),
    sa.Column('sha', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], onupdate='NO ACTION', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('commit_id')
    )
    op.create_table('Group',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('group_pw', sa.String(length=255), nullable=True),
    sa.Column('member_maxCnt', sa.Integer(), nullable=True),
    sa.Column('member_counter', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['Users.user_id'], onupdate='NO ACTION'),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('History',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_num', sa.String(length=255), nullable=False),
    sa.Column('solve_time', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], onupdate='NO ACTION', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('Participate',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['Group.group_id'], onupdate='NO ACTION', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], onupdate='NO ACTION', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Participate')
    op.drop_table('History')
    op.drop_table('Group')
    op.drop_table('Commit')
    op.drop_table('Users')
    # ### end Alembic commands ###
