"""add index on commit_date

Revision ID: a5474dcca4a9
Revises: 982bf9b83b5e
Create Date: 2026-03-15 14:20:51.767145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5474dcca4a9'
down_revision = '982bf9b83b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Commit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Commit_commit_date'), ['commit_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Commit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Commit_commit_date'))

    # ### end Alembic commands ###
